"""Generate the build-only credentials header from Secretspec variables."""

import json
import os
from pathlib import Path

REQUIRED_SECRETS = {
    "WIFI_SSID": "WIFI_SSID",
    "WIFI_PWD": "WIFI_PASSWORD",
    "MQTT_USERNAME": "MQTT_USERNAME",
    "MQTT_PASSWORD": "MQTT_PASSWORD",
}


def generate_secrets_header() -> None:
    missing = [source for source in REQUIRED_SECRETS.values() if not os.environ.get(source)]
    if missing:
        names = ", ".join(missing)
        raise RuntimeError(
            f"Missing Secretspec environment variable(s): {names}. "
            "Build with: secretspec run -- platformio run"
        )

    # PlatformIO runs extra scripts from the project directory. SCons does not
    # define __file__ for scripts loaded through SConscript.
    project_dir = Path.cwd()
    header = project_dir / "src" / "secrets.h"
    content = "// Generated by scripts/generate_secrets.py; do not edit or commit.\n"
    for macro, source in REQUIRED_SECRETS.items():
        content += f"#define {macro} {json.dumps(os.environ[source])}\n"

    header.write_text(content, encoding="utf-8")


generate_secrets_header()
